<a href="https://colab.research.google.com/github/hyunjung-kim0524/DL_Study/blob/main/20240426_2_4_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%97%B0%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

데이터 연산

In [6]:
import numpy as np

vector_a = [1,2]
vector_b = [3,4]

print("vector_a :", vector_a)
print("vector_b :", vector_b)

print("vector_a + vector_b :", np.add(vector_a, vector_b))
print("vector_a - vector_b :", np.subtract(vector_a, vector_b))
print("vector_a * vector_b :", np.multiply(vector_a, vector_b))
print("vector_a / vector_b :", np.divide(vector_a, vector_b))

vector_a : [1, 2]
vector_b : [3, 4]
vector_a + vector_b : [4 6]
vector_a - vector_b : [-2 -2]
vector_a * vector_b : [3 8]
vector_a / vector_b : [0.33333333 0.5       ]


In [12]:
matrix_a = np.arange(1,5).reshape(2,2)
matrix_b = np.arange(5,9).reshape(2,2)

print("matrix_a :", matrix_a, sep='\n')
print("\nmatrix_b :", matrix_b, sep='\n')

print("\nmatrix_a + matrix_b :", np.add(matrix_a, matrix_b), sep='\n')
print("\nmatrix_a - matrix_b :", np.subtract(matrix_a, matrix_b), sep='\n')
print("\nmatrix_a * matrix_b :", np.multiply(matrix_a, matrix_b), sep='\n')
print("\nmatrix_a / matrix_b :", np.divide(matrix_a, matrix_b), sep='\n')

matrix_a :
[[1 2]
 [3 4]]

matrix_b :
[[5 6]
 [7 8]]

matrix_a + matrix_b :
[[ 6  8]
 [10 12]]

matrix_a - matrix_b :
[[-4 -4]
 [-4 -4]]

matrix_a * matrix_b :
[[ 5 12]
 [21 32]]

matrix_a / matrix_b :
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [15]:
vector_a = np.arange(1, 10, 3)  # 1 ~ 10까지 3개 차이만큼 vector 생성
vector_b = np.arange(1, 10, 4)

print("vector_a : ", vector_a, sep='\n')
print("vector_b : ", vector_b, sep='\n')

print("vector_a == vector_b : ", vector_a == vector_b, sep='\n')
print("vector_a < vector_b : ", vector_a < vector_b, sep='\n')
print("vector_a > vector_b : ", vector_a > vector_b, sep='\n')

vector_a : 
[1 4 7]
vector_b : 
[1 5 9]
vector_a == vector_b : 
[ True False False]
vector_a < vector_b : 
[False  True  True]
vector_a > vector_b : 
[False False False]


In [4]:
import numpy as np

vector_nan = np.empty((2, 2))

print(vector_nan)
print(np.isnan(vector_nan))

# 두번째 열을 null 값으로 대체함

vector_nan[:, 1] = np.nan

print(vector_nan)
print(np.isnan(vector_nan))

[[4.89141778e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]]
[[False False]
 [False False]]
[[4.89141778e-310             nan]
 [0.00000000e+000             nan]]
[[False  True]
 [False  True]]


In [15]:
import numpy as np

a=1
b=2

# scalar 곱하기
print("scalar 곱하기 : ", np.multiply(a,b))

# 행렬 곱하기
print("scalar 행렬 곱하기 :", np.dot(a,b))

a=np.arange(1,3)
b=np.arange(1,3)

print("\na : ",a)
print("\nb : ",b)

# 벡터의 곱셈 : (1*1) + (2*2) = 5.
# 벡터의 곱 : (1*1, 2*2) = (1,4)
print("\n벡터의 곳셈 : ", np.multiply(a,b)) # 벡터 곱셈
print("\n벡터의 곱 : ", np.dot(a,b)) # 벡터 곱

scalar 곱하기 :  2
scalar 행렬 곱하기 : 2

a :  [1 2]

b :  [1 2]

벡터의 곳셈 :  [1 4]

행렬의 곱 :  5


In [19]:
import numpy as np

a = np.arange(1,5).reshape(2,2)
b = np.arange(1,5).reshape(2,2)

print("a : ", a, sep='\n')
print("\nb : ", b, sep='\n')

print("\na * b 곱셈 : ", np.multiply(a, b), sep='\n')
print("\na * b 곱 : ", np.dot(a, b), sep='\n')

a : 
[[1 2]
 [3 4]]

b : 
[[1 2]
 [3 4]]

a * b 곱셈 : 
[[ 1  4]
 [ 9 16]]

a * b 곱 : 
[[ 7 10]
 [15 22]]


In [25]:
# 브로드캐스팅 : 다른 형상을 가진 배열간의 연산. 더 작은 배열을 자동으로 더 큰 배열의 형상에 맞게 확장시켜 연산을 수행

import numpy as np

a = np.arange(1,5)
b = np.arange(1,3)

print("a : ", a, sep='\n')
print("\nb : ", b, sep='\n')


# print(np.add(a,b))  ---> 두 베열의 크기가 동일하지 않아 브로드캐스팅이 되지 않음. 배열간의 연산이 불가능함

#브로드캐스팅이 가능한 경우
# 1. 행렬 * 스칼라
a = np.arange(1,7).reshape(2,3) # 행렬 (2x3)
b = 1                           # 스칼라
print('a', a, sep='\n')
print('\n a + 1', a + b, sep='\n')


# 2. 행렬 * 행렬
 #    2.1 행렬의 축 하나가 1차원인 경우(2*3, 1*2)
a = np.arange(1,7).reshape(2,3) # 행렬 (2x3)
b = np.arange(1,4).reshape(1,3) # 행렬 (1x3)
c = np.arange(1,3).reshape(2,1) # 행렬 (2x1)

print('a', a, sep='\n')
print('b', b, sep='\n')
print('c', c, sep='\n')

print('\n a + b', a + b, sep='\n')
print('\n a + c', a + c, sep='\n')


 #    2.2 행렬의 차원의 짝이 맞는 경우(1*2, 2*1)

a = np.arange(1,3).reshape(1,2) # 행렬 (1x2)
b = np.arange(1,3).reshape(2,1) # 행렬 (2x1)

print('a', a, sep='\n')
print('b', b, sep='\n')

print('\n a + b', a + b, sep='\n')


a : 
[1 2 3 4]

b : 
[1 2]
a
[[1 2 3]
 [4 5 6]]

 a + 1
[[2 3 4]
 [5 6 7]]
a
[[1 2 3]
 [4 5 6]]
b
[[1 2 3]]
c
[[1]
 [2]]

 a + b
[[2 4 6]
 [5 7 9]]

 a + c
[[2 3 4]
 [6 7 8]]
a
[[1 2]]
b
[[1]
 [2]]

 a + b
[[2 3]
 [3 4]]
