<a href="https://colab.research.google.com/github/hyunjung-kim0524/DL_Study/blob/main/20240425_2_3_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%9D%B8%EB%8D%B1%EC%8B%B1%EA%B3%BC_%EC%8A%AC%EB%9D%BC%EC%9D%B4%EC%8B%B1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

데이터 인덱싱

In [4]:
import numpy as np

array = np.arange(10)

print(array[0])
print(array[-1])

0
9


In [6]:
array_25 = np.reshape(array,[2,5])
print(array_25[0])
print(array_25[-1])

[0 1 2 3 4]
[5 6 7 8 9]


데이터 슬라이싱

In [8]:
import numpy as np

array_25 = np.reshape(np.arange(10), (2,5))
print(array_25)

print('\narray_25[:, 0]: ', array[:, 0])
print('\narray_25[:, 1]: ', array[:, 1])

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [2]:
import numpy as np

array = np.arange(24)
array = array.reshape(2,3,4)

print("\narray shape :", array.shape)
print("\narray[0,0,0] :", array[0,0,0])
print("\narray[1,2,3] :", array[1,2,3])  # [차원, 행, 렬]


array shape : (2, 3, 4)

array[0,0,0] : 0

array[1,2,3] : 23
