<a href="https://colab.research.google.com/github/hyunjung-kim0524/DL_Study/blob/main/20240425_2_2_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%9E%90%EB%A3%8C%ED%98%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

데이터 자료형 - 벡터를 1차원 텐서로 변환

In [3]:
import tensorflow as tf

vector_float64 = tf.constant([183,89,26.58], dtype=tf.float64)
vector_float32 = tf.constant([183,89,26.58], dtype=tf.float32)
vector_float16 = tf.constant([183,89,26.58], dtype=tf.float16)

vector_uint8 = tf.cast(vector_float64, dtype=tf.uint8)  # 실수형 데이터가 정수형으로 변경됨

print(vector_float64)
print(vector_float32)
print(vector_float16)
print(vector_uint8)


tf.Tensor([183.    89.    26.58], shape=(3,), dtype=float64)
tf.Tensor([183.    89.    26.58], shape=(3,), dtype=float32)
tf.Tensor([183.    89.    26.58], shape=(3,), dtype=float16)
tf.Tensor([183  89  26], shape=(3,), dtype=uint8)


In [5]:
import numpy as np

vector_float64 = np.array([183, 89, 26.58], dtype = np.float64)
vector_float32 = vector_float64.astype('float32')
vector_float16 = vector_float64.astype('float16')

vector_uint8 = vector_float64.astype('uint8')      # 실수형 데이터가 정수형으로 변경됨

print(vector_float64, vector_float64.dtype.type(vector_float64))
print(vector_float32, vector_float32.dtype.type(vector_float64))
print(vector_float16, vector_float16.dtype.type(vector_float64))
print(vector_uint8, vector_uint8.dtype.type(vector_float64))

[183.    89.    26.58] [183.    89.    26.58]
[183.    89.    26.58] [183.    89.    26.58]
[183.    89.    26.58] [183.    89.    26.58]
[183  89  26] [183  89  26]


데이터 형상 변경

In [9]:
import numpy as np

array = np.arange(10)  # 0 ~ 9까지의 배열로 생성

print(array)
print("array.ndim :", array.ndim)  # 배열의 차원 출력
print("array.shape :", array.shape)   # 배열의 형상 출력

[0 1 2 3 4 5 6 7 8 9]
array.ndim : 1
array.shape : (10,)


In [11]:
# 2차원으로 형상 변경하기 : reshape

array_25 = np.reshape(array,(2,5))
array_52 = np.reshape(array,(5, 2))

print(array_25)
print("array.ndim :", array_25.ndim)  # 배열의 차원 출력
print("array.shape :", array_25.shape)   # 배열의 형상 출력

print('\n')
print(array_52)
print("array.ndim :", array_52.ndim)  # 배열의 차원 출력
print("array.shape :", array_52.shape)   # 배열의 형상 출력

[[0 1 2 3 4]
 [5 6 7 8 9]]
array.ndim : 2
array.shape : (2, 5)


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
array.ndim : 2
array.shape : (5, 2)


In [14]:
# 3차원으로 형상 변경하기 : reshape

array = np.arange(0,24,1) # 0 부터 24까지 1간격으로 배열 생성

print(array)
print("array.ndim :", array.ndim)  # 배열의 차원 출력
print("array.shape :", array.shape)   # 배열의 형상 출력

array = array.reshape(4,3,2)  # 3X2의 배열을 4개 생성

print('\n')
print(array)
print("array.ndim :", array.ndim)  # 배열의 차원 출력
print("array.shape :", array.shape)   # 배열의 형상 출력

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
array.ndim : 1
array.shape : (24,)


[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
array.ndim : 3
array.shape : (4, 3, 2)


In [20]:
import numpy as np

array = np.zeros((5,5))
array[:, 2] = 255  # 2열을 255로 변경.. 이미지를 숫자형태의 데이터셋으로 변경할때 0부터 255로 표현하

print(array)
print(array.shape)


# 하나의 특성을 가지는 이미지를 딥러닝 모델에 입력하기 위하여 1차원 배열(벡터)로 변환
array.reshape(-1)  # 원본 데이터 변경
print('array.flatten : \n', array.flatten())  # 복사한 데이터만 변경. 주어진 배열의 복사본을 반환
print('array.ravel : \n', array.ravel())  # 원본 데이터 변경

[[  0.   0. 255.   0.   0.]
 [  0.   0. 255.   0.   0.]
 [  0.   0. 255.   0.   0.]
 [  0.   0. 255.   0.   0.]
 [  0.   0. 255.   0.   0.]]
(5, 5)
array.flatten : 
 [  0.   0. 255.   0.   0.   0.   0. 255.   0.   0.   0.   0. 255.   0.
   0.   0.   0. 255.   0.   0.   0.   0. 255.   0.   0.]
array.ravel : 
 [  0.   0. 255.   0.   0.   0.   0. 255.   0.   0.   0.   0. 255.   0.
   0.   0.   0. 255.   0.   0.   0.   0. 255.   0.   0.]
