<a href="https://colab.research.google.com/github/hyunjung-kim0524/DL_Study/blob/main/20240425_2_1_%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%9E%90%EB%A3%8C_%EA%B5%AC%EC%A1%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Scalar : 하나의 정수나 실수를 갖는 값

In [2]:
import tensorflow as tf

scalar_cm = tf.constant(183)  # tf.constant : 상수 텐서를 생성하는 함수. 숫자형, 문자형, 배열 모두 사용 가능
scalar_kg = tf.constant(89)
scalar_bmi = tf.constant(26.58)

# 텐서 출력
print(scalar_cm)
print(scalar_kg)
print(scalar_bmi)

# 0차원 텐서를 numpy 함수로 변환
scalar_numpy = scalar_cm.numpy()

print(scalar_numpy)
type(scalar_numpy)

tf.Tensor(183, shape=(), dtype=int32)
tf.Tensor(89, shape=(), dtype=int32)
tf.Tensor(26.58, shape=(), dtype=float32)
183


numpy.int32

벡터 : 크기와 방향을 가지는 값. 1차원 배열로 생성됨

In [4]:
import tensorflow as tf

# 벡터 텐서 출력
vector = tf.constant([183 ,89, 26.58])
print(vector)

# numpy 변환
vector_numpy = vector.numpy()

print(vector_numpy)
type(vector_numpy)

tf.Tensor([183.    89.    26.58], shape=(3,), dtype=float32)
[183.    89.    26.58]


numpy.ndarray

행렬 : 행과 열을 가진 2차원 배열

In [8]:
import tensorflow as tf

matrix=tf.constant([[182, 99, 29.89],
                   [183, 89, 26.58]])

print(matrix)

matrix_numpy = matrix.numpy()

print(matrix_numpy)
type(matrix_numpy)

tf.Tensor(
[[182.    99.    29.89]
 [183.    89.    26.58]], shape=(2, 3), dtype=float32)
[[182.    99.    29.89]
 [183.    89.    26.58]]


numpy.ndarray

텐서 : 축이 3개 이상인 데이터 구조

In [11]:
import tensorflow as tf

tensor = tf.constant([
    [[183, 94, 29.07], [183, 89, 26.58]],
    [[182, 86, 25.68], [183, 87, 25.98]],
    [[183, 97, 28.07], [183, 99, 29.56]],
    [[183, 100, 29.86], [183, 96, 28.67]],
])

print(tensor)

tensor_numpy = tensor.numpy()

print(tensor_numpy)
type(tensor_numpy)

tf.Tensor(
[[[183.    94.    29.07]
  [183.    89.    26.58]]

 [[182.    86.    25.68]
  [183.    87.    25.98]]

 [[183.    97.    28.07]
  [183.    99.    29.56]]

 [[183.   100.    29.86]
  [183.    96.    28.67]]], shape=(4, 2, 3), dtype=float32)
[[[183.    94.    29.07]
  [183.    89.    26.58]]

 [[182.    86.    25.68]
  [183.    87.    25.98]]

 [[183.    97.    28.07]
  [183.    99.    29.56]]

 [[183.   100.    29.86]
  [183.    96.    28.67]]]


numpy.ndarray